### ISSUE TITLE
WinRAR 7.01已发布，期待更新

### ISSUE THREAD

**Issue by Femtometer** [n2far2000/winrarsc#13]
Null

**Comment by n2far2000** [comment]
简体中文更新暂未发布

**Comment by chenyiping1995** [comment]
7.01 简体中文版已发布 @n2far2000 

https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20240528/wrr/winrar-x32-701sc.exe
https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20240528/rrlb/winrar-x32-701sc.exe

https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20240528/wrr/winrar-x64-701sc.exe
https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20240528/rrlb/winrar-x64-701sc.exe

**Comment by pzhlkj6612** [comment]
Link to the PR: #14 .
