### ISSUE TITLE
下载注册了还是弹广告

### ISSUE THREAD

**Issue by AcaciusJosiah** [n2far2000/winrarsc#3]

**Comment by n2far2000** [comment]
请提供版本号

**Comment by AcaciusJosiah** [comment]
> 请提供版本号

在你提供的链接那里下载可以了 在这两个网站下载的都不行
![1641460995(1)](https://user-images.githubusercontent.com/96288219/148360306-308175d2-7bd0-4214-bcdc-56ac5ecb432c.png)

**Comment by n2far2000** [comment]
请仔细阅读文章内容
