### ISSUE TITLE
关于“rrlb”版本和“wrr”版本的区别

### ISSUE THREAD

**Issue by ShinjoKurumi** [n2far2000/winrarsc#5]
最近本人联系 WinRAR 官方支持，询问了有关”rrlb”版本和“wrr”版本区别的问题，并得到了答复。“rrlb”和”wrr“两个版本区分了购买来源，前者代表程序是从 RaRLaB.com 购买的，而后者是从 Win-RaR.com 购买的。两者没有功能性的区别。

而本仓库的 README.md 是这样描述的，说法存在错误：
> rrlb是开发版，wrr是发行正式版

建议改正一下。

**Comment by n2far2000** [comment]
已修改，感谢
