### ISSUE TITLE
winrar 7.0版本有链接嘛

### ISSUE THREAD

**Issue by raijintt** [n2far2000/winrarsc#9]

**Comment by ZLHuo** [comment]
https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20240306/wrr/winrar-x32-700sc.exe
https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20240306/wrr/winrar-x64-700sc.exe

**Comment by raijintt** [comment]
谢谢大佬
